### ISSUE TITLE
service install should process cwd

### ISSUE THREAD

**Issue by pekeler** [bruhs/caddy-service#1]
When I set up a folder for my website with a Caddyfile, and then `caddy -service install`, the generated /etc/systemd/system/Caddy.service should include the -root parameter or set the WorkingDirectory so that the service finds my folder and the Caddyfile.

Right now, this service ignores my Caddyfile and starts up with the default config (`http://:2015`).

**Comment by hacdias** [comment]
Hello @pekeler! Thanks for mentioning this! I've pushed a possible fix for this (it is supposed to work with all flags now 😄). We'll just need to wait for @fabiofcferreira to update the plugin in `caddyserver.com`!

**Comment by fabiofcferreira** [comment]
Hey there, @pekeler! We've tried to deploy the new version of caddy-service but unfortunately we are unable to do it right now due to a bug on the build server. We are waiting for a fix but we'll reach you as soon as this problem is solved.
Thanks for your patience!

**Comment by fabiofcferreira** [comment]
Hey there (again) @pekeler! We're very happy to tell you the fixed version of caddy-service is now available to download. Sorry for the delay. If have any other questions/tips concerning our plugin feel free to contact us.
Thanks for using our plugin!
