### ISSUE TITLE
Command 'caddy -service start' don't start service

### ISSUE THREAD

**Issue by reducio** [bruhs/caddy-service#10]
Hello!
I start command `caddy -service start` in folder on production server, but service don't start.
I don't get warning message and service caddy don't start. If I do write command `caddy -host mysite.com` in my work folder on production server, it everything works. How to diagnostic my problem?
Thanks for answer.

![image](https://user-images.githubusercontent.com/6662917/30774296-151138ca-a089-11e7-819a-d17c3bfebed1.png)

**Comment by fabiofcferreira** [comment]
Hey there!
Maybe that isn't the problem, but I think I have to ask: have you installed `caddy-service` with `caddy -service install -name customName`? Make sure your Caddyfile's syntax is OK and that you specify the path to it (if its filename is different than Caddyfile).

Thanks for using our plugin. 😄

**Comment by reducio** [comment]
@fabiofcferreira yes, I download build caddy with [hook.service](https://caddyserver.com/docs/hook.service), otherwise, I would can't use command `caddy -service install` and `caddy -service start`. But I don't have Caddyfile, because I think that if I start command in work folder it don't need Caddyfile. 😄

**Comment by tobya** [comment]
@krypton-code to simplify things always specify caddyfile with -conf when using the service.

**Comment by reducio** [comment]
@tobya @fabiofcferreira I run command, tell me please, what I doing wrong?
If I run simply `caddy`, it service is working. This means that Caddyfile is correct.

![image](https://user-images.githubusercontent.com/6662917/30774947-ffee79ee-a092-11e7-8333-6140ebfbeab4.png)

![image](https://user-images.githubusercontent.com/6662917/30774963-219a1814-a093-11e7-8232-163dc26fb09a.png)

**Comment by tobya** [comment]
The value are set when you install the service so if you don't set them right on install you need to uninstall and reinstall - do this

    caddy -service uninstall

    caddy -service install -log mylogfile.log -conf mycaddyfile

    caddy -service start

It is really worth adding -log mylogfile.txt to see what errors if any caddy is throwing.  Otherwise you will never see them.

@fabiofcferreira @hacdias  is it possible to update the readme a little for a bit more direction for users.

**Comment by reducio** [comment]
@tobya excellent, it is working! Thank you very much! 
It would be great if it's written in docs.
Caddy-service is cool package. 😄

**Comment by fabiofcferreira** [comment]
Hey! :)
We've updated docs to ease the setup and experience.

Thanks for your contribution!  :heart:
