### ISSUE TITLE
Enhancement for Caddyfile syntax

### ISSUE THREAD

**Issue by reducio** [bruhs/caddy-service#11]
Hey!
I noticed singularity in settings Caddyfile. 

When I write this syntax - everything is working: 
`localhost:8080 {`
`     root /Users/root/workflow/site`
`}`

if I write this syntax:
`localhost:8080 {`
`     root ~/workflow/site`
`}`

I get 404 error.
This subtlety not described in docs.
Thanks for reading =)

**Comment by fabiofcferreira** [comment]
Hi there!
According to the data you've provided, I can only assume that it might be a problem of the user home folder you're running Caddy from (because ` ~/ ` is an alias of the user home folder).

Thanks 😄

**Comment by reducio** [comment]
@fabiofcferreira I mean the same thing. Why not use an alias?
Because such a desire can appear not only for me. And this is not described in the docs and could complicate the search for errors.

**Comment by tobya** [comment]
@krypton-code I think this suggestion might be best on the https://caddy.community site or posted as an issue on github.com/mholt/caddy as it is relevant to the caddy project as a whole rather than just the service plugin.

**Comment by reducio** [comment]
@tobya thanks, my problem is solved: https://caddy.community/t/i-noticed-singularity-in-settings-caddyfile/2798/2
