### ISSUE TITLE
Windows 上安装多个服务，只能启动一个服务

### ISSUE THREAD

**Issue by xiaomochen520** [bruhs/caddy-service#12]
### 如下图所示：
![image](https://user-images.githubusercontent.com/24455233/32156782-6c4425c2-bd7a-11e7-8189-20d490ddfbae.png)
###  我在windows上安装了三个服务分别是 server00 server01 server02 ，但是我只能启动一个服务。当我尝试启动第二个服务的时候，报错信息如下：
![image](https://user-images.githubusercontent.com/24455233/32156827-9852c8bc-bd7a-11e7-974d-88d81fac10b2.png)

**Comment by hacdias** [comment]
Hey @xiaomochen520! The same way you can't run Caddy twice at once, you can't also start two Caddy services at once with the same port. You **must** have different ports in your Caddyfiles.

**Comment by xiaomochen520** [comment]
@hacdias  I installed two Caddy locations are different, configuration files are not the same, of course, the port is not the same. One port is 80, one port is 8080, one port is 8081, and the 80 port acts as a proxy like nginx. Sorry, my English is not very good. These are from translation. I don't know if I can express myself correctly.

**Comment by hacdias** [comment]
Did you set the Caddyfile when you installed the services using `-conf` flag?

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
