### ISSUE TITLE
No longer works on Windows

### ISSUE THREAD

**Issue by MHHenriksen** [bruhs/caddy-service#13]
Downloading a new build from https://caddyserver.com/download and including only the hook.service plugin, extracting to C:/caddy/, then creating a service using `caddy.exe -service install -conf Caddyfile` (and the Caddyfile only contains localhost:80), I am not able to start the service. The event log shows an error with the message:
> The Caddy service terminated with the following service-specific error: 
Incorrect function.

Full event data:
```xml
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7024</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2017-11-01T13:28:20.355603800Z" /> 
  <EventRecordID>8154</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="1076" ThreadID="24728" /> 
  <Channel>System</Channel> 
  <Computer>laptop</Computer> 
  <Security /> 
  </System>
 <EventData>
  <Data Name="param1">Caddy</Data> 
  <Data Name="param2">%%1</Data> 
  <Binary>430061006400640079000000</Binary> 
  </EventData>
  </Event>
```

Tested on Windows 10 Creators Update as well as Fall Creators Update. Tried with logging as well, but it looks like the executable never runs at all.

Tested 32 and 64 bit, both fail the same way.

When running the same Caddy build normally in a console, it works fine.

**Comment by hacdias** [comment]
You **must** use the full path for your Caddyfile when installing the service.
