### ISSUE TITLE
Windows: service ignores CaddyFile in same folder as executable

### ISSUE THREAD

**Issue by nickrsan** [bruhs/caddy-service#14]
Hi there,

First, thanks for making this extension, it's great. I just had the following symptoms, and wasn't sure if it was a bug, or just needed to be documented (in which case, I can submit a PR with a change).

On Windows 10, x64, I am able to run Caddy and have it load my caddyfile, which specifies to listen on port 8005. When I run Caddy manually, everything works and it listens on 8005 only. 

I was able to install and start the service with the default command: `caddy.exe -service install` and `caddy.exe -service start`. The service also appears in Windows services manager as started, and I can interact with it there too. But Caddy isn't listening on 8005 in that case. Through some inspection, I saw that Caddy was listening on its default 2015 instead. When I uninstalled the service and reinstalled it with `caddy.exe -service install -conf path\to\my\CaddyFile` everything worked as expected. Caddy listened on 8005 and not 2015. the CaddyFile is in the same folder as caddy.exe, so I would expect the default to be that it picks up the CaddyFile.

My CaddyFile is simple, in case it's relevant:
```
:8005/static {
	tls off
	log ./caddy_access.log
	errors visible
	root C:/Code/icefish_backend/icefish/static
}
```

Is this expected behavior, or is this a bug? If it's expected, would you be open to a PR making the behavior clearer? Thanks again for the extension!

**Comment by hacdias** [comment]
Sorry! It is the expected behavior since the current working directory when the service starts may not be the same as where the executable is. You *must* always set the `-conf` flag. I'll add that to the docs now. Thanks 😄
