### ISSUE TITLE
Unable to start as a service

### ISSUE THREAD

**Issue by Wozarib** [bruhs/caddy-service#18]
Hi!

Hopefully the solution to this is pretty simple. It won't start as a service, and fails with this in the Event Viewer:

The Caddy service terminated with service-specific error Incorrect function..

When installing the service I am using the following:

C:\caddy>caddy.exe -service install -conf C:\caddy\Caddyfile

Am I doing something wrong here?

**Comment by tobya** [comment]
Can you start it using the caddyfile by just running Caddy.exe without installing as a service?

>  caddy.exe -conf C:\caddy\Caddyfile

If not what errors do you get?   What is you complete unaltered caddyfile?

**Comment by Wozarib** [comment]
I can run it fine if I do the following from the folder where the executable is: caddy.exe -conf C:\caddy\Caddyfile. I haven't added it to PATH yet, but that's fine as it hasn't given me any issues so far not having it there (unless the service somehow requires that?)

If I install it as a service but do not specify a caddyfile, it runs fine but uses the default config (localhost:2015) as you'd expect. 

The service when specifying the caddyfile looks like this:
![image](https://user-images.githubusercontent.com/1272498/38214942-08d12194-36be-11e8-97b8-4645ce7b0b46.png)

If I try to start it, I get the following:
![image](https://user-images.githubusercontent.com/1272498/38214977-2419ad22-36be-11e8-8418-d246ea2bfe2a.png)

My caddyfile is:
![image](https://user-images.githubusercontent.com/1272498/38215104-96cc2480-36be-11e8-9463-4ab7f87d5f92.png)

**Comment by tobya** [comment]
You need to output the log so you can see any potential issues.

- Uninstall the service
- Reinstall the service and add a log file `c:\path\caddy.exe -conf c:\path\caddyfile -log c:\path\log.log

This may give you an idication of what is preventing caddy from loading

**Comment by peewee5** [comment]
I have encountered the same problem and this my log output after messing around with the file in question:

```
2018/05/17 01:42:21 [ERROR] Persisting instance UUID: open C:\WINDOWS\system32\config\systemprofile\.caddy\uuid: The system cannot find the path specified.

2018/05/17 01:45:54 [ERROR] Reading persistent UUID: read C:\WINDOWS\system32\config\systemprofile\.caddy\uuid: The handle is invalid.

2018/05/17 01:45:54 [ERROR] Persisting instance UUID: open C:\WINDOWS\system32\config\systemprofile\.caddy\uuid: is a directory

2018/05/17 01:47:47 [ERROR] Parsing UUID: invalid UUID length: 0
```

**Comment by Wozarib** [comment]
@peewee5 my solution was to specify the absolute path for the logging directive. 

Previously it was:

`log logs/xxx.xxx.xxx.228.log`

Changed it to: 
`log C:\caddy\logs\xxx.xxx.xxx.228.log`

Once I'd done that, starting it from the services dialogue worked fine and I haven't had any issues since.

**Comment by peewee5** [comment]
@Wozarib thanks for the update.  2 quick questions, is the IP address in your Caddyfile the internal IP of your server?  In the first line of your Caddyfile, what is port 8080 in this case, for you?

**Comment by peewee5** [comment]
I went ahead and tried to validate my Caddyfile as well to see if that would provide any additional insight and this is what I got: 
```
PS D:\caddy> .\caddy.exe -validate
Activating privacy features... [www.aomosk.com] failed to get certificate: [www.aomosk.com] error presenting token: presenting with standard HTTP provider server: Could not start HTTP server for challenge -> listen tcp :80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

I've checked netstat and the resource monitor in windows and it doesn't show anything listening on port 80 or port 443.

**Comment by Wozarib** [comment]
@peewee5 the addresses in my caddy file are both my external address and internal address. I just use port forwarding to the internal address from my external address when I want to access it externally

It inspects the incoming headers to see if there's a match to one of the virtual hosts in the caddy file - if I didn't specify my internal address, when I browse to it locally from a PC on my network it'll just say the following when I browse to the machines local IP address:

`404 Site 192.168.0.150:8080 is not served on this interface`

So I created a virtual host there to avoid that. I could browse to the external IP address, negating the need for the internal one to be defined, but it's just the way I chose to do it.

My external IP is there as well instead of a domain name so that when I browse to it on port 8080 I can see the content served. Normally you might use a domain name there that you own that's pointing to your IP address, but putting a domain there causes Caddy to try and set up an SSL certificate for it, which I don't need, and using just the IP address prevents that.

Port 8080 is just the port I chose for it to run on. You can use whatever port you like I believe.

**Comment by Wozarib** [comment]
Just looking at your last post - are you running it with an elevated command prompt? That might be why it can't start if you're not.

**Comment by peewee5** [comment]
Yes, I tried running it as admin from PowerShell and just the command prompt itself.

**Comment by hummerpj** [comment]
Seems the I had the same problem.  The solution was to specify both `-email` and `-agree` arguments in the cli when setting up the service.

I've been banging my head against the wall on this one for days.  Had issues using both `nssm` and `hook.service` plugin to create this as a service.

The last post in this thread on the Caddy forums pointed me in the right direction.

https://caddy.community/t/caddy-unable-to-start-as-a-service-on-window-server-2008-r2/3646/37

Here is what works for me after trying lots of solutions.  Run this from an admin console.

```

caddy -service install -agree -conf C:\Cadd\CaddyFile -log C:\Caddy\logs\caddylog.log -email myemail@email.com

```

These two flags are required for registering certs with Let's Encrypt.  Actually the email is supposed to be optional per the docs but I couldn't start the service without it.

**Comment by hacdias** [comment]
Thanks for the info @hummerpj!

Could you all check if the solution proposed by @hummerpj works for you so we can close this issue? 😄

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
