### ISSUE TITLE
Passing a "bad" action should report an error

### ISSUE THREAD

**Issue by timothywlewis** [bruhs/caddy-service#2]
Steps to reproduce:
1. Run "caddy -service restart" before running "caddy -service install"

Expected behavior:
Caddy should report the invalid state and exit immediately

Actual results:
Caddy starts running web service as if the -service flag hadn't been passed

---

This was specifically tested on Windows 10 but probably misbehaves similarly on other OSes.

---

Analysis: I haven't written anything in golang yet, but my guess is the if block following `err = service.Control(s, action)` should do an `os.Exit(1)` after printing the err to stderr rather than returning the err to the Caddy hook invoker.

**Comment by hacdias** [comment]
Hello, hello! Thank you for this!

**Comment by hacdias** [comment]
Thanks! I have to ask @fabiofcferreira to update this on the server to be available ASAP 😄

**Comment by fabiofcferreira** [comment]
Hey there @timothywlewis! The new version of caddy-service is now available. :)
Thanks for helping making this plugin better!

**Comment by timothywlewis** [comment]
Awesome! Thanks @hacdias and @fabiofcferreira!
