### ISSUE TITLE
Use of Service Plugin prevents on Startup from running

### ISSUE THREAD

**Issue by tobya** [bruhs/caddy-service#21]
I recently downloaded 0.10.14 and now 0.11 and included the Service plugin.  

Any command set to run `on startup` is not run.

    hello.azure.cookingisfun.ie:8080 {
       tls off
       on startup "myfile.bat" &
     }

If I run 0.11 without the service plugin included the myfile.bat file is executed.  Perhaps @elcore might be able to help track down where the issue is.

I am using windows.

**Comment by elcore** [comment]
Hello @tobya,

https://github.com/hacdias/caddy-service/blob/3fecbe69fdf6b58275b519348b44598a6a9cc4d9/service.go#L34-L38

Here @hacdias needs to add

```
// Execute instantiation events
caddy.EmitEvent(caddy.InstanceStartupEvent, instance)
```

We could add `caddy.EmitEvent(caddy.InstanceStartupEvent, instance)` to `caddy.Start(cdyfile Input)`

**Comment by tobya** [comment]
It appears this is an issue in Caddy.  I'll leave it open here until PR is merged.

**Comment by elcore** [comment]
> It appears this is an issue in Caddy. I'll leave it open here until PR is merged.

It is not an issue in Caddy, it is just better implement it there 😄

**Comment by elcore** [comment]
> It appears this is an issue in Caddy. I'll leave it open here until PR is merged.

It is not an issue directly in Caddy.

There are two ways to fix this:

1. See PR

2. Add `caddy.EmitEvent(caddy.InstanceStartupEvent, instance)` to

https://github.com/hacdias/caddy-service/blob/3fecbe69fdf6b58275b519348b44598a6a9cc4d9/service.go#L34-L38

ping @mholt

**Comment by mholt** [comment]
Thanks Eldin! How does that fix the problem, exactly?

**Comment by elcore** [comment]
The service plugin does not emit the `caddy.InstanceStartupEvent` on which the on plugin relies.

**Comment by elcore** [comment]
https://github.com/mholt/caddy/blob/73273c5bf81b3962aec314f8b6988cccb7089a5a/caddy/caddymain/run.go#L157-L164 vs https://github.com/hacdias/caddy-service/blob/3fecbe69fdf6b58275b519348b44598a6a9cc4d9/service.go#L34-L38

**Comment by mholt** [comment]
I don't follow. Does the Run() function not execute with the service plugin?

**Comment by elcore** [comment]
> I don't follow. Does the Run() function not execute with the service plugin?

As far as I understand the service plugin, it hijacks the Run() function after https://github.com/mholt/caddy/blob/73273c5bf81b3962aec314f8b6988cccb7089a5a/caddy/caddymain/run.go#L137-L138, and creates its own instance (see above).

**Comment by elcore** [comment]
The service plugin basically manages its own instances.

As I have said above, there are two ways to fix this, I prefer No. 2, as the plugin manages its own instances.

**Comment by hacdias** [comment]
I'm following the conversation. If you both think it's better to do the 1st option - https://github.com/mholt/caddy/pull/2161#issuecomment-397438241 - you can merge it. Otherwise I can add that line here!

**Comment by Rubyj** [comment]
@elcore @hacdias @mholt I have tried implementing both of these solutions (the PR and the modification to caddy-service) and building from source. Unfortunately, neither of the fixes cause startup to run successfully when using the service plugin.

**Comment by elcore** [comment]
Closed in https://github.com/mholt/caddy/pull/2161
