### ISSUE TITLE
Allow caddy-service to be run as specific user and from specific working dir

### ISSUE THREAD

**Issue by Rubyj** [bruhs/caddy-service#24]
For my service, I am required to use a specific working dir and a specific user. Using caddy-service, there is no way to configure this. I have to manually edit the systemd file and add my extra `WorkingDirectory=` and `User=` arguments. I would like to request the ability to add arguments to the service file created (such as these to start) so I do not have to manually edit the systemd file and can use caddy-service as wrapper to this functionality.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
