### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by luisalvarado** [bruhs/caddy-service#28]
Hi and awesome work on this buddy. Here is some feedback about my experience to see if this helps with a couple of deployment issues.

If I may, I think I see several minor issues here that when using -service install should be addressed to make it easier for faster deployment. When using the hook.service, caddy -service install should do the following to fix several issues at once:

When it creates the service (using systemd for example) it should also create a default folder for the SSL certificates and a default for the caddyserver file. Like /etc/caddy/ssl for the ssl files and /etc/caddy for the conf file. (As a bonus it should by default be renamed to caddy.service, not Caddy.service (Capital C there).

The default conf folder is to avoid having to guess or manually add the conf parameter.

The default ssl folder is to avoid having several issues when doing the whole systemd process as a it fails if it cant find the folders.

There should be a default log in /var/log/caddy (default with option to set somewhere else, same for conf and ssl folders).

Did not check but an option to automatically restart if the caddyserver file is updated or changed (same option to check if caddyserver file has correct format, if not, do not restart service but send a warning to the logs. If all is good, automatically restart service)

This are just a couple of things that would help in deployment.

**Comment by fabiofcferreira** [comment]
The service name issue has been solved. However, until further notice the folder structure is not yet done. I'll get back to this issue as soon as I can.
Thanks for your help improving this plugin 😄

**Comment by luisalvarado** [comment]
Well it is an amazing one. So thank you

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
