### ISSUE TITLE
Is the service restart handled gracefully?

### ISSUE THREAD

**Issue by maxiride** [bruhs/caddy-service#30]
I've [read ](https://caddyserver.com/docs/cli)in the Caddy documentation that it can be reloaded with the signal `USR1`, here I quote:

```
USR1
Reloads the configuration file, then gracefully restarts the server. 
If there is an error with the new configuration, the error is logged and the configuration 
rolls back with zero downtime.
```

Since the `caddy -service restart [-name optionalName]` only takes the optional argument name I suppose I can't pass that signal here.

In [this](https://stackoverflow.com/a/40185007) answer an approach is suggested, however, while peeking around `service.go` I didn't understand how the restart is handled. And in case if such method can be implemented.

**Comment by tobya** [comment]
Graceful restarts are not supported on Windows so it is not possible for the service to restart gracefully either.

**Comment by maxiride** [comment]
Ok, I get then that I should carefully test my caddyfile before attempting a restart or everything will not be reachable anymore.

**Comment by tobya** [comment]
You can use `caddy -validate` which will catch most stuff such as syntax errors etc, but not 100%
