### ISSUE TITLE
Cannot get service to start with custom SSL (not LetsEncrypt)

### ISSUE THREAD

**Issue by ninja6o4** [bruhs/caddy-service#32]
Running Windows Server 2016; I own my own SSL for my domain so I shouldn't need -agree and -email for LetsEncrypt (not using it.) 
The configuration works when run manually.

Installed the services with cmd-line: 
`caddy -service install -conf C:\Caddy\Caddyfile -log C:\Caddy\ServiceRun.log`
Attempts to start results in "incorrect function" in Event Viewer, no Caddy log is created.
If I leave out the conf file, it does start but (obviously) doesn't use the correct conf.

conf file contents:
```
mega.mydomain.com {
proxy / 127.0.0.1:5000 {
  transparent
  }
tls C:\caddy\_mydomain_com.crt C:\caddy\_mydomain_com.key
}
```

I did see the other thread outlining this issue but having the -agree and e-mail flags don't help.

**Comment by tobya** [comment]
Can you run caddy without service plugin? 

> caddy conf=c:\caddy\caddyfile 

Do you get the same error

Does it start with 

> tls self_signed

**Comment by ninja6o4** [comment]
When I run it manually with the conf file, it starts up fine and uses my cert as logged. It is a wildcard SSL if it makes any difference..

```
2019/07/14 16:34:13 [INFO][cache:0xc0001c22d0] Started certificate maintenance routine
2019/07/14 16:34:14 [INFO] Successfully loaded TLS assets from C:\caddy\_mydomain_com.crt and C:\caddy\_mydomain_com.key
2019/07/14 16:34:14 [INFO] Serving https://mega.mydomain.com:2015 
```

**Comment by tobya** [comment]
A workaround until this issue is looked at would be to run without using the service.

**Comment by ninja6o4** [comment]
OK, hopefully it's an easy fix to merge in eventually.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
