### ISSUE TITLE
How to  use Caadyfile in caddy service

### ISSUE THREAD

**Issue by zuohuadong** [bruhs/caddy-service#4]
```
caddy -service start Caddy

```

where is  Caddyfile？

**Comment by tobya** [comment]
@zuohuadong  Presumably in the same directory as the Caddy executable.

**Comment by hacdias** [comment]
Thanks @tobya 😄 

@zuohuadong and when you install the service for the first time, the flags you use in the command will be the same that the service will use. So, if you run:

```
caddy -service install -conf c:/Caddyfile
```

Every time the service starts it will use `c:/Caddyfile` for configuration.

**Comment by tobya** [comment]
Actually I'm wrong it wont use the caddyfile from the directory, it is from somewhere else.

To ensure this works always specify the caddyfile as above.

**Comment by hacdias** [comment]
Sorry! @zuohuadong by default it will use the Caddyfile in the current working directory. That's just how Caddy works. This plugin only adds a service into it, nothing else. The Caddyfile part is still done by Caddy itself.

Since I don't know where the current working directory for services is on each OS, you should, as @tobya said, always specify the Caddyfile via flag.

Sorry for the mistake before 😞

**Comment by tobya** [comment]
I think caddy works by using the caddyfile in the directory which the caddy executable resides in, which is not necessarily the working directory.  The service does not load the caddyfile from the executable directory, and must be specified.

I think it would be good to update docs to say that it is *essential* to specify the caddyfile eg update the command install to this in the docs

    caddy -service install [-name optionalName] -conf="c:\caddy\Caddyfile" -log "c:\caddy\logs\caddyservice.log"

**Comment by hacdias** [comment]
For what I know Caddy always uses the Caddyfile from the working directory
if not specified. I always have the executable in a separate folder only
for binaries and whenever I run Caddy command it will use the Caddyfile on
the cwd.

Thanks for the suggestion! We'll add a note for that. ☺️
