### ISSUE TITLE
whers is Caddyfile

### ISSUE THREAD

**Issue by zuohuadong** [bruhs/caddy-service#6]
(centos 7)
Install  caddy  
```
curl https://getcaddy.com | bash -s hook.service,http.git
```
Then 
```
caddy -service install
```
so,where is my Caddyfile?

**Comment by zuohuadong** [comment]
in 
```
/etc/local/bin/Caddyfile
```
?

**Comment by hacdias** [comment]
Hello @zuohuadong! Check the issue #4 please 😄 Hope it helps! Soon we'll clarify this on the docs.
